server:
  port: 8080

spring:
  application:
    name: cloudsnows-gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848